---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    semver: '>=4.0.0'
  url: https://github.com/stefanprodan/podinfo
